name: Deploy

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: npm

      # - run: npm ci

      # - name: Type check
      #   run: npx tsc -b

      # - name: Lint
      #   run: npm run lint

      # - name: Build
      #   run: npm run build

      - name: Deploy to Forge
        if: success()
        run: curl -s "${{ secrets.FORGE_DEPLOY_URL }}"
